# Generated by Django 5.0.6 on 2024-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agence_name', models.CharField(max_length=20)),
                ('addresse', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
