# Generated by Django 5.0.6 on 2024-06-21 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_agences'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='agence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='insurance.agences'),
            preserve_default=False,
        ),
    ]
