# Generated by Django 5.0.6 on 2024-06-21 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('insurance', '0006_policyrecord_agence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRecordList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=500)),
                ('total_amount', models.PositiveIntegerField()),
                ('promised_date', models.DateField(auto_now=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.agences')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='Policy_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='insurance.policyrecordlist'),
            preserve_default=False,
        ),
    ]
